title: the Simplex theme
logo_img: /assets/img/icons/simplex_logo.svg
favicon: /assets/favicon.ico
description: description
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © m0oogi 2021

sass:
    style: compressed

baseUrl: "https://m0oogi.github.io/"

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"